name: Deploy API Docs to Bump.sh

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        
      - name: Install dependencies
        run: uv sync --dev
        
      - name: Generate OpenAPI spec
        run: uv run python scripts/generate_openapi.py
        
      - name: Deploy to Bump.sh
        uses: bump-sh/github-action@v1
        with:
          doc: ${{ secrets.BUMP_DOC_ID }}
          token: ${{ secrets.BUMP_TOKEN }}
          file: openapi.json